buildings.push({
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                153.1767580046931,
                -27.667053042305326
              ],
              [
                153.1768164103982,
                -27.666989368883744
              ],
              [
                153.176707379613,
                -27.66691084293625
              ],
              [
                153.17664897400743,
                -27.666974516295035
              ],
              [
                153.1767580046931,
                -27.667053042305326
              ]
            ]
          ],
          [
            [
              [
                153.17669149696326,
                -27.66716417823404
              ],
              [
                153.1767083070332,
                -27.667145852097857
              ],
              [
                153.17675511888382,
                -27.66717956685278
              ],
              [
                153.17679486843235,
                -27.667136232274494
              ],
              [
                153.17674805667951,
                -27.66710251749916
              ],
              [
                153.17675933028005,
                -27.66709022714878
              ],
              [
                153.17662497335402,
                -27.66699346071483
              ],
              [
                153.1765571401599,
                -27.667067411731846
              ],
              [
                153.17669149696326,
                -27.66716417823404
              ]
            ]
          ]
        ]
      },
      "properties": {
        "address": "3920 Pacific Hwy, Loganholme QLD 4129",
        "centroid": {
          "latitude": -27.667089369381245,
          "longitude": 153.17667406318003
        },
        "isAutoGenerated": true
      }
    }
  ]
});
buildings.push({
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [
      153.17667406318003,
      -27.667089369381245
    ]
  },
  "properties": {
    "description": "3920 Pacific Hwy, Loganholme QLD 4129",
    "partner": "Locatrix Plans SDK Partner",
    "client": "ACME Robots",
    "campus": "ACME Robots",
    "building": "AI Brain Training",
    "siteplan": "https://api.locatrix.com/plans-embed/v1/plan?interactive=true&viewerToken=djE6YWxsQXJlYXM6cGxuX3dpYXIybGY4ZXZnNnhzdmRnMzEybjViZTQ6cHRucl8wZGpraHAxamxoMzE2cjNuNDhhbHduenA5OjE3Nzk4NTMzOTYsZmQ3MWFiNjQtZjJkMi00ZjM1LTQ5YWMtNWQ3MGZmNDIyN2IwLDdTdWIyYlE4SWcyUCUyZnk0RzZHQ0ZxWmVVSjglMmZOJTJiY05iR0ZmYVlUb2IzQzglM2Q=",
    "floors": [
      {
        "name": "Ground Level",
        "link": "https://api.locatrix.com/plans-embed/v1/plan?layers=structure,equipment,zone&interactive=true&viewerToken=djE6YWxsQXJlYXM6cGxuX2l3cjBkbzlvcjV5bThzdnhxeHJyYzdheGw6cHRucl8wZGpraHAxamxoMzE2cjNuNDhhbHduenA5OjE3Nzk4NTMzOTcsZmQ3MWFiNjQtZjJkMi00ZjM1LTQ5YWMtNWQ3MGZmNDIyN2IwLHBnZ2dsVGV6VmhVcFNjMEpkdDlPQVdlaEwyZkt5cE5DbUhpcm5memNnVDAlM2Q="
      }
    ]
  }
});
buildings.push({
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                153.17621798804072,
                -27.666336000101015
              ],
              [
                153.17619899972573,
                -27.66631769163175
              ],
              [
                153.17612303383606,
                -27.66637955422127
              ],
              [
                153.1761420221423,
                -27.66639786254789
              ],
              [
                153.17607513409195,
                -27.666452332582736
              ],
              [
                153.1760561458355,
                -27.666434024230696
              ],
              [
                153.17585905512476,
                -27.66659452420402
              ],
              [
                153.17600073862803,
                -27.66673113361616
              ],
              [
                153.17641959113843,
                -27.66639004455689
              ],
              [
                153.1762968958363,
                -27.66627174189793
              ],
              [
                153.17621798804072,
                -27.666336000101015
              ]
            ]
          ]
        ]
      },
      "properties": {
        "address": "3914 Pacific Hwy, Loganholme QLD 4129",
        "centroid": {
          "latitude": -27.66649922992842,
          "longitude": 153.17613734986838
        },
        "isAutoGenerated": true
      }
    }
  ]
});
buildings.push({
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [
      153.17613734986838,
      -27.66649922992842
    ]
  },
  "properties": {
    "description": "3914 Pacific Hwy, Loganholme QLD 4129",
    "partner": "Locatrix Plans SDK Partner",
    "client": "ACME Robots",
    "campus": "ACME Robots",
    "building": "Arm Assembly",
    "siteplan": "https://api.locatrix.com/plans-embed/v1/plan?interactive=true&viewerToken=djE6YWxsQXJlYXM6cGxuX3dpYXIybGY4ZXZnNnhzdmRnMzEybjViZTQ6cHRucl8wZGpraHAxamxoMzE2cjNuNDhhbHduenA5OjE3Nzk4NTM0MDEsZmQ3MWFiNjQtZjJkMi00ZjM1LTQ5YWMtNWQ3MGZmNDIyN2IwLGRWb1V5elhRbmliZTM1cWp3bkRoaXRhbFJVdENWYnFMVklRZE51dkphZHclM2Q=",
    "floors": [
      {
        "name": "Ground Level",
        "link": "https://api.locatrix.com/plans-embed/v1/plan?layers=structure,equipment,zone&interactive=true&viewerToken=djE6YWxsQXJlYXM6cGxuXzFjajU1dDdzZTVsZWMyMjM1NGV5ajFwYnQ6cHRucl8wZGpraHAxamxoMzE2cjNuNDhhbHduenA5OjE3Nzk4NTM0MDMsZmQ3MWFiNjQtZjJkMi00ZjM1LTQ5YWMtNWQ3MGZmNDIyN2IwLFo2bkZWQzJNVmlGdGI2QmtuRldaWWIlMmZONHJFSjBocmtMck9yYVVXMEtadyUzZA=="
      }
    ]
  }
});
buildings.push({
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                153.1760943402004,
                -27.66670965956946
              ],
              [
                153.17616758180753,
                -27.666780278291487
              ],
              [
                153.1761576789704,
                -27.666788342640803
              ],
              [
                153.17621951706883,
                -27.666847965786616
              ],
              [
                153.1762590310263,
                -27.666815787931235
              ],
              [
                153.17626856749933,
                -27.666824982945602
              ],
              [
                153.17647417521061,
                -27.666657548292214
              ],
              [
                153.17632955951115,
                -27.666518110341013
              ],
              [
                153.1760943402004,
                -27.66670965956946
              ]
            ]
          ]
        ]
      },
      "properties": {
        "address": "3916 Pacific Hwy, Loganholme QLD 4129",
        "centroid": {
          "latitude": -27.66668470702174,
          "longitude": 153.17628293046715
        },
        "isAutoGenerated": true
      }
    }
  ]
});
buildings.push({
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [
      153.17628293046715,
      -27.66668470702174
    ]
  },
  "properties": {
    "description": "3916 Pacific Hwy, Loganholme QLD 4129",
    "partner": "Locatrix Plans SDK Partner",
    "client": "ACME Robots",
    "campus": "ACME Robots",
    "building": "Body Assembly",
    "siteplan": "https://api.locatrix.com/plans-embed/v1/plan?interactive=true&viewerToken=djE6YWxsQXJlYXM6cGxuX3dpYXIybGY4ZXZnNnhzdmRnMzEybjViZTQ6cHRucl8wZGpraHAxamxoMzE2cjNuNDhhbHduenA5OjE3Nzk4NTM0MDcsZmQ3MWFiNjQtZjJkMi00ZjM1LTQ5YWMtNWQ3MGZmNDIyN2IwLG5vRlFZbDM2bFZ4UU1BU3d0bnZMdlJUJTJmUDMlMmZpM1pYWUpVVWFHYUt2Q0NzJTNk",
    "floors": [
      {
        "name": "Ground Level",
        "link": "https://api.locatrix.com/plans-embed/v1/plan?layers=structure,equipment,zone&interactive=true&viewerToken=djE6YWxsQXJlYXM6cGxuXzNkd3BrMmgwb3BhbDU2cWNqbzJxMXBneWk6cHRucl8wZGpraHAxamxoMzE2cjNuNDhhbHduenA5OjE3Nzk4NTM0MDgsZmQ3MWFiNjQtZjJkMi00ZjM1LTQ5YWMtNWQ3MGZmNDIyN2IwLEU4c0VUa0JmUVlKZ0M5MGtGdE5ZVmU5c1lONjJ2RGwxSSUyYjFQV2dhb20zQSUzZA=="
      }
    ]
  }
});
buildings.push({
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                153.1764848010145,
                -27.66685504183511
              ],
              [
                153.17651488588837,
                -27.666856166826523
              ],
              [
                153.1765137286876,
                -27.666880464225002
              ],
              [
                153.1764524306813,
                -27.66687817199153
              ],
              [
                153.17644815030752,
                -27.666968043278487
              ],
              [
                153.17656881241163,
                -27.66697255554359
              ],
              [
                153.17656954614029,
                -27.666957150086475
              ],
              [
                153.1765912987487,
                -27.666957963522712
              ],
              [
                153.17661081824394,
                -27.666942067986927
              ],
              [
                153.1766179049868,
                -27.666793253893726
              ],
              [
                153.17648797506547,
                -27.666788395431166
              ],
              [
                153.1764848010145,
                -27.66685504183511
              ]
            ]
          ],
          [
            [
              [
                153.17631336011306,
                -27.66713453659352
              ],
              [
                153.17642098615624,
                -27.667105913692815
              ],
              [
                153.17636207737627,
                -27.666931993947973
              ],
              [
                153.17625445155363,
                -27.666960616835638
              ],
              [
                153.17631336011306,
                -27.66713453659352
              ]
            ]
          ]
        ]
      },
      "properties": {
        "address": "3918 Pacific Hwy, Loganholme QLD 4129",
        "centroid": {
          "latitude": -27.666883862634872,
          "longitude": 153.17653935391792
        },
        "isAutoGenerated": true
      }
    }
  ]
});
buildings.push({
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [
      153.17653935391792,
      -27.666883862634872
    ]
  },
  "properties": {
    "description": "3918 Pacific Hwy, Loganholme QLD 4129",
    "partner": "Locatrix Plans SDK Partner",
    "client": "ACME Robots",
    "campus": "ACME Robots",
    "building": "Head Assembly",
    "siteplan": "https://api.locatrix.com/plans-embed/v1/plan?interactive=true&viewerToken=djE6YWxsQXJlYXM6cGxuX3dpYXIybGY4ZXZnNnhzdmRnMzEybjViZTQ6cHRucl8wZGpraHAxamxoMzE2cjNuNDhhbHduenA5OjE3Nzk4NTM0MTIsZmQ3MWFiNjQtZjJkMi00ZjM1LTQ5YWMtNWQ3MGZmNDIyN2IwLG9McWw4QkNDTkMxa203Njl2Sm9QN0RSV2FBQld6cUFZeVlZR1prVkFydGMlM2Q=",
    "floors": [
      {
        "name": "Ground Level",
        "link": "https://api.locatrix.com/plans-embed/v1/plan?layers=structure,equipment,zone&interactive=true&viewerToken=djE6YWxsQXJlYXM6cGxuX2VzaWw3Yjg4eW1rdnYzazd0Y2lvdWc2aHU6cHRucl8wZGpraHAxamxoMzE2cjNuNDhhbHduenA5OjE3Nzk4NTM0MTMsZmQ3MWFiNjQtZjJkMi00ZjM1LTQ5YWMtNWQ3MGZmNDIyN2IwLHU0dXJyJTJiWmNlZ29CY3RPOXR3NTFKbExXTTkxQ0IlMmYlMmZVeERSUCUyZiUyZkgwdGI0JTNk"
      }
    ]
  }
});
buildings.push({
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                153.17571092792986,
                -27.666427237816144
              ],
              [
                153.17578593868973,
                -27.666499562847502
              ],
              [
                153.17584007429593,
                -27.66645547783384
              ],
              [
                153.175878354911,
                -27.666492387907358
              ],
              [
                153.17608798402944,
                -27.66632167793782
              ],
              [
                153.17597469252507,
                -27.666212442837892
              ],
              [
                153.17571092792986,
                -27.666427237816144
              ]
            ]
          ]
        ]
      },
      "properties": {
        "address": "3912 Pacific Hwy, Loganholme QLD 4129",
        "centroid": {
          "latitude": -27.666365402649106,
          "longitude": 153.17590447171125
        },
        "isAutoGenerated": true
      }
    }
  ]
});
buildings.push({
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [
      153.17590447171125,
      -27.666365402649106
    ]
  },
  "properties": {
    "description": "3912 Pacific Hwy, Loganholme QLD 4129",
    "partner": "Locatrix Plans SDK Partner",
    "client": "ACME Robots",
    "campus": "ACME Robots",
    "building": "Leg Assembly",
    "siteplan": "https://api.locatrix.com/plans-embed/v1/plan?interactive=true&viewerToken=djE6YWxsQXJlYXM6cGxuX3dpYXIybGY4ZXZnNnhzdmRnMzEybjViZTQ6cHRucl8wZGpraHAxamxoMzE2cjNuNDhhbHduenA5OjE3Nzk4NTM0MTYsZmQ3MWFiNjQtZjJkMi00ZjM1LTQ5YWMtNWQ3MGZmNDIyN2IwLHhVUHolMmIxNTNxcTZWZ2gxUTBpbDZ0b0RZR3V5SnhPaloxdTZkY0hlZjFuNCUzZA==",
    "floors": [
      {
        "name": "Ground Level",
        "link": "https://api.locatrix.com/plans-embed/v1/plan?layers=structure,equipment,zone&interactive=true&viewerToken=djE6YWxsQXJlYXM6cGxuX2lyMzRzcDA2MWFxZXV5ZXNoc3N5cGdxcm86cHRucl8wZGpraHAxamxoMzE2cjNuNDhhbHduenA5OjE3Nzk4NTM0MTcsZmQ3MWFiNjQtZjJkMi00ZjM1LTQ5YWMtNWQ3MGZmNDIyN2IwLCUyYld2YlRDMGFjRkwwU29LUU9Bc1dWZG5IbUJHU01JMjNCZiUyZnlzVXllTCUyZjQlM2Q="
      }
    ]
  }
});
buildings.push({
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                153.18619395375754,
                -27.67753582951881
              ],
              [
                153.18605921756324,
                -27.67728722064241
              ],
              [
                153.18604501660536,
                -27.67729326043114
              ],
              [
                153.18602008476745,
                -27.677247257451675
              ],
              [
                153.185957884765,
                -27.677273711575317
              ],
              [
                153.1859828165198,
                -27.67731971465518
              ],
              [
                153.18595980869554,
                -27.67732950007638
              ],
              [
                153.1860945445746,
                -27.677578108990655
              ],
              [
                153.18619395375754,
                -27.67753582951881
              ]
            ]
          ]
        ]
      },
      "properties": {
        "address": "4032 Pacific Hwy, Loganholme QLD 4129",
        "centroid": {
          "latitude": -27.677417185244302,
          "longitude": 153.1860690540534
        },
        "isAutoGenerated": false
      }
    }
  ]
});
buildings.push({
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [
      153.1860690540534,
      -27.677417185244302
    ]
  },
  "properties": {
    "description": "4032 Pacific Hwy, Loganholme QLD 4129",
    "partner": "Locatrix Plans SDK Partner",
    "client": "The Art of Science",
    "campus": "Neptune's Bounty",
    "building": "Reception and Office ",
    "siteplan": "https://api.locatrix.com/plans-embed/v1/plan?interactive=true&viewerToken=djE6YWxsQXJlYXM6cGxuX3V2am05YXQ3MjI3bjlraXY2b2FvZTB3cjY6cHRucl8wZGpraHAxamxoMzE2cjNuNDhhbHduenA5OjE3Nzk4NTM0MjMsZmQ3MWFiNjQtZjJkMi00ZjM1LTQ5YWMtNWQ3MGZmNDIyN2IwLG9TWGV5c0tyOW83UGJnQVloUFlRaXRqaDk1OFBaWWsySkhTSHFtUWljRDglM2Q=",
    "floors": [
      {
        "name": "Ground Level",
        "link": "https://api.locatrix.com/plans-embed/v1/plan?layers=structure,equipment,zone&interactive=true&viewerToken=djE6YWxsQXJlYXM6cGxuX3FzMTBveWh3bjlxeGkwcTA2aTFtOWhnMW86cHRucl8wZGpraHAxamxoMzE2cjNuNDhhbHduenA5OjE3Nzk4NTM0MjUsZmQ3MWFiNjQtZjJkMi00ZjM1LTQ5YWMtNWQ3MGZmNDIyN2IwLFJPVFFtejIxYkdNRDlnQSUyYjY5V3ltVEhHdjVpWnZOOExleFhoZmpUcTlsZyUzZA=="
      }
    ]
  }
});
buildings.push({
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                153.185990143315,
                -27.677190870714263
              ],
              [
                153.18596260108285,
                -27.677140060013393
              ],
              [
                153.18588259798452,
                -27.6771740921608
              ],
              [
                153.18591014021672,
                -27.67722490284581
              ],
              [
                153.185990143315,
                -27.677190870714263
              ]
            ]
          ]
        ]
      },
      "properties": {
        "address": "4032 Pacific Hwy, Loganholme QLD 4129",
        "centroid": {
          "latitude": -27.67718248143785,
          "longitude": 153.18593637064976
        },
        "isAutoGenerated": false
      }
    }
  ]
});
buildings.push({
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [
      153.18593637064976,
      -27.67718248143785
    ]
  },
  "properties": {
    "description": "4032 Pacific Hwy, Loganholme QLD 4129",
    "partner": "Locatrix Plans SDK Partner",
    "client": "The Art of Science",
    "campus": "Neptune's Bounty",
    "building": "Guard House",
    "siteplan": "https://api.locatrix.com/plans-embed/v1/plan?interactive=true&viewerToken=djE6YWxsQXJlYXM6cGxuX3V2am05YXQ3MjI3bjlraXY2b2FvZTB3cjY6cHRucl8wZGpraHAxamxoMzE2cjNuNDhhbHduenA5OjE3Nzk4NTM0MjgsZmQ3MWFiNjQtZjJkMi00ZjM1LTQ5YWMtNWQ3MGZmNDIyN2IwLGZsOGcxVlglMmJ1JTJmVm9qYXdzdGM4M1JndFo2eHpSMWRSJTJiVG5PSHd5JTJidW9EQSUzZA==",
    "floors": [
      {
        "name": "Ground Level",
        "link": "https://api.locatrix.com/plans-embed/v1/plan?layers=structure,equipment,zone&interactive=true&viewerToken=djE6YWxsQXJlYXM6cGxuXzgzNjZpYXc3eXdqYjZqdjM1bnQxNTBkM286cHRucl8wZGpraHAxamxoMzE2cjNuNDhhbHduenA5OjE3Nzk4NTM0MzAsZmQ3MWFiNjQtZjJkMi00ZjM1LTQ5YWMtNWQ3MGZmNDIyN2IwLFVGMzZzbWRvZW01TzNBYThyNmRTYmhkcTl6YmlqVm9sZVlrS0NrWmJNS1klM2Q="
      }
    ]
  }
});
buildings.push({
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                153.18642652552307,
                -27.677569699483126
              ],
              [
                153.18618901818184,
                -27.677127717695566
              ],
              [
                153.18607393565537,
                -27.67717624877377
              ],
              [
                153.1863114429966,
                -27.677618230364992
              ],
              [
                153.18642652552307,
                -27.677569699483126
              ]
            ]
          ]
        ]
      },
      "properties": {
        "address": "4032 Pacific Hwy, Loganholme QLD 4129",
        "centroid": {
          "latitude": -27.677372974305623,
          "longitude": 153.18625023058922
        },
        "isAutoGenerated": false
      }
    }
  ]
});
buildings.push({
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [
      153.18625023058922,
      -27.677372974305623
    ]
  },
  "properties": {
    "description": "4032 Pacific Hwy, Loganholme QLD 4129",
    "partner": "Locatrix Plans SDK Partner",
    "client": "The Art of Science",
    "campus": "Neptune's Bounty",
    "building": "Block A",
    "siteplan": "https://api.locatrix.com/plans-embed/v1/plan?interactive=true&viewerToken=djE6YWxsQXJlYXM6cGxuX3V2am05YXQ3MjI3bjlraXY2b2FvZTB3cjY6cHRucl8wZGpraHAxamxoMzE2cjNuNDhhbHduenA5OjE3Nzk4NTM0MzMsZmQ3MWFiNjQtZjJkMi00ZjM1LTQ5YWMtNWQ3MGZmNDIyN2IwLDdveFolMmZnaDRXWmtERENZTW01JTJibUcwbVA0WXRKTEpjT2E5WDNsZkVtSXprJTNk",
    "floors": [
      {
        "name": "Ground Level",
        "link": "https://api.locatrix.com/plans-embed/v1/plan?layers=structure,equipment,zone&interactive=true&viewerToken=djE6YWxsQXJlYXM6cGxuX3BnZGowdXU5cGI1OGJoN2kyd2czN3R0ZTY6cHRucl8wZGpraHAxamxoMzE2cjNuNDhhbHduenA5OjE3Nzk4NTM0MzQsZmQ3MWFiNjQtZjJkMi00ZjM1LTQ5YWMtNWQ3MGZmNDIyN2IwLEE3SGpQQ0xaSTRXQXFuWUNqWSUyZkRpTmdEd1k0JTJiRXFDJTJmSThKeHcwdzlFRWMlM2Q="
      }
    ]
  }
});
buildings.push({
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                153.18643647365786,
                -27.677286413462888
              ],
              [
                153.18636293037417,
                -27.677234320436735
              ],
              [
                153.18634325430372,
                -27.677256119642436
              ],
              [
                153.18636753228748,
                -27.677273316522765
              ],
              [
                153.18634848338223,
                -27.677294420833242
              ],
              [
                153.18639774862152,
                -27.677329316978934
              ],
              [
                153.18643647365786,
                -27.677286413462888
              ]
            ]
          ]
        ]
      },
      "properties": {
        "address": "4032 Pacific Hwy, Loganholme QLD 4129",
        "centroid": {
          "latitude": -27.677283088253834,
          "longitude": 153.1863870222565
        },
        "isAutoGenerated": false
      }
    }
  ]
});
buildings.push({
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [
      153.1863870222565,
      -27.677283088253834
    ]
  },
  "properties": {
    "description": "4032 Pacific Hwy, Loganholme QLD 4129",
    "partner": "Locatrix Plans SDK Partner",
    "client": "The Art of Science",
    "campus": "Neptune's Bounty",
    "building": "Block C 1",
    "siteplan": "https://api.locatrix.com/plans-embed/v1/plan?interactive=true&viewerToken=djE6YWxsQXJlYXM6cGxuX3V2am05YXQ3MjI3bjlraXY2b2FvZTB3cjY6cHRucl8wZGpraHAxamxoMzE2cjNuNDhhbHduenA5OjE3Nzk4NTM0MzgsZmQ3MWFiNjQtZjJkMi00ZjM1LTQ5YWMtNWQ3MGZmNDIyN2IwLGFGVDRLdDFldjRVT0ZWWDd1Y0dJaFNNRkpnUGlwZktoaW5tNCUyZnVEYllkcyUzZA==",
    "floors": [
      {
        "name": "Ground Level",
        "link": "https://api.locatrix.com/plans-embed/v1/plan?layers=structure,equipment,zone&interactive=true&viewerToken=djE6YWxsQXJlYXM6cGxuXzM4OTl5ZGgwMmNwNmw4MXd1dm1wamNpYnk6cHRucl8wZGpraHAxamxoMzE2cjNuNDhhbHduenA5OjE3Nzk4NTM0MzksZmQ3MWFiNjQtZjJkMi00ZjM1LTQ5YWMtNWQ3MGZmNDIyN2IwLG9USk56Rzl6OUltWDZHdWdJZUxaUXFEUU9ZdFZYczFaVlF2N2hTSlNicUElM2Q="
      }
    ]
  }
});
buildings.push({
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                153.18651986502965,
                -27.677345482298147
              ],
              [
                153.18644599105335,
                -27.677293155000022
              ],
              [
                153.18638788619626,
                -27.677357529433277
              ],
              [
                153.18642572742033,
                -27.67738433353804
              ],
              [
                153.18640659311671,
                -27.67740553243998
              ],
              [
                153.1864426259944,
                -27.67743105565559
              ],
              [
                153.18651986502965,
                -27.677345482298147
              ]
            ]
          ]
        ]
      },
      "properties": {
        "address": "4032 Pacific Hwy, Loganholme QLD 4129",
        "centroid": {
          "latitude": -27.677359282043263,
          "longitude": 153.1864511494246
        },
        "isAutoGenerated": false
      }
    }
  ]
});
buildings.push({
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [
      153.1864511494246,
      -27.677359282043263
    ]
  },
  "properties": {
    "description": "4032 Pacific Hwy, Loganholme QLD 4129",
    "partner": "Locatrix Plans SDK Partner",
    "client": "The Art of Science",
    "campus": "Neptune's Bounty",
    "building": "Block C 2",
    "siteplan": "https://api.locatrix.com/plans-embed/v1/plan?interactive=true&viewerToken=djE6YWxsQXJlYXM6cGxuX3V2am05YXQ3MjI3bjlraXY2b2FvZTB3cjY6cHRucl8wZGpraHAxamxoMzE2cjNuNDhhbHduenA5OjE3Nzk4NTM0NDQsZmQ3MWFiNjQtZjJkMi00ZjM1LTQ5YWMtNWQ3MGZmNDIyN2IwLCUyYkN1SEtaNzRZVGxVRGtqR25XNXI5MVNZajBKYmtWdXl6VXElMmYwa1hNVVBjJTNk",
    "floors": [
      {
        "name": "Ground Level",
        "link": "https://api.locatrix.com/plans-embed/v1/plan?layers=structure,equipment,zone&interactive=true&viewerToken=djE6YWxsQXJlYXM6cGxuXzdpa2g2aHEzNGdja3FpNzF5ZDhrbXh0cGw6cHRucl8wZGpraHAxamxoMzE2cjNuNDhhbHduenA5OjE3Nzk4NTM0NDYsZmQ3MWFiNjQtZjJkMi00ZjM1LTQ5YWMtNWQ3MGZmNDIyN2IwLEtzMnVuUWdRaG42JTJibDVlNmFwVUolMmZkU0tjdzR2S1p4TUVWcEd1YyUyYkpFaUklM2Q="
      }
    ]
  }
});
buildings.push({
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                153.18660388714653,
                -27.677404997757748
       