using System.Collections.Generic;

namespace esapi_building_footprints
{
    class OutlineModels
    {
        public class BuildingOutlinesGeoJson
        {
            public string Type { get; set; }
            public List<Feature> Features { get; set; }
            public string GeoJson { get; set; }
        }

        public class Feature
        {
            public string Type { get; set; }
            public Geometry Geometry { get; set; }
            public Properties Properties { get; set; }
        }

        public class Geometry
        {
            public string Type { get; set; }
            public List<List<List<List<double>>>> Coordinates { get; set; }
        }

        public class Properties
        {
            public bool IsAutoGenerated { get; set; }
        }

    }
}
