using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace esapi_building_footprints
{
    public class PlanMetadata
    {
        [JsonIgnore] public string PlanCode { get; set; }
        public DateTime UpdatedAt { get; set; }
        public int Revision { get; set; }
        public int SchemaVersion { get; set; }
        public int YouAreHereCount { get; set; }
        public int AssemblyAreaCount { get; set; }
        public int EntityCount { get; set; }
        public int ExitSignsCount { get; set; }
        public List<MetaEvacSign> EvacSigns { get; set; }
        public SpatialMetadata SpatialMetadata { get; set; }
        public List<EquipmentSummary> EquipmentSummary { get; set; }
        public List<EquipmentMetadata> EquipmentMetadata { get; set; }
    }

    public class MetaEvacSign
    {
        public string SignRef { get; set; }
        public string SignType { get; set; }
        public string Template { get; set; }
        public string TemplateCode { get; set; }
        public bool ShowPrivateZones { get; set; }
    }

    public class BuildingOutlines
    {
        public BuildingFootprint BuildingFootprint { get; set; }
        [JsonProperty("spatialMetadata")] public BuildingSpatialMetadata[] BuildingSpatialMetadata { get; set; }
    }

    public class BuildingOutlinesGeoJson
    {
        [JsonProperty("type")] 
        public string Type { get; set; }
        public List<Feature> Features { get; set; }
    }

    public class BuildingFootprint
    {
        public bool IsAutoGenerated { get; set; }
        public Polygons Polygons { get; set; }
        public Point Centroid { get; set; }
    }

    public class BuildingSpatialMetadata
    {
        public double[] BoundingBox { get; set; }
        public List<Zones> Zones { get; set; }
        public BillableInteriorArea BillableInteriorArea { get; set; }
    }

    public class SpatialMetadata
    {
        public double[] BoundingBox { get; set; }
        public List<MetadataZone> Zones { get; set; }
        public List<FootprintMetadata> PlanFootprints { get; set; }
        public List<FootprintMetadata> FloorFootprints { get; set; }
        public List<BuildingFootprintsMetadata> BuildingFootprints { get; set; }
        public BillableInteriorArea BillableInteriorArea { get; set; }
    }

    public class EquipmentSummary
    {
        public string IconType { get; set; }
        public int count { get; set; }
    }

    public class EquipmentMetadata
    {
        public Dictionary<string, string> Metadata { get; set; }
    }

    public class MetadataZone : SquareMetersPolygons
    {
        public string ZoneType { get; set; }
    }

    public class FootprintMetadata : SquareMetersPolygons
    {
        public string PlanCode { get; set; }
    }

    public class SquareMetersPolygons
    {
        public double? SquareMeters { get; set; }
        public Polygons Polygons { get; set; }
    }

    public class Polygons
    {
        [JsonProperty("type")]
        public string Type { get; set; }
        [JsonProperty("coordinates")]
        public List<List<List<List<double>>>> Coordinates { get; set; }
    }

    public class Zones
    {
        public string ZoneType { get; set; }
        public double? SquareMeters { get; set; }
        public Polygons Polygons { get; set; }
    }

    public class BillableInteriorArea
    {
        public double SquareMeters { get; set; }
        public int Pixels { get; set; }
        public int PixelsPerSquareMeter { get; set; }
        public bool TransparentPixelsCounted { get; set; }
    }

    public class Feature
    {
        [JsonProperty("type")]
        public string Type { get; set; }
        public Geometry Geometry { get; set; }
        public Properties Properties { get; set; }
    }

    public class Geometry
    {
        [JsonProperty("type")]
        public string Type { get; set; }
        [JsonProperty("coordinates")]
        public List<List<List<List<double>>>> Coordinates { get; set; }
    }

    public class Properties
    {
        public string Address { get; set; }
        public Centroid Centroid { get; set; }
        public bool IsAutoGenerated { get; set; }
    }

    public class Centroid
    {
        public double Latitude { get; set; }
        public double Longitude { get; set; }
    }

    public class BuildingFootprintsMetadata
    {
        public string BuildingCode { get; set; }
        public double SquareMeters { get; set; }
        public MultiPolygon Polygons { get; set; }
        public Point Centroid { get; set; }
        public List<string> FootprintPlanCodes { get; set; }
    }

    public class MultiPolygon
    {
        [JsonProperty("type")]
        public string Type { get; set; }
        [JsonProperty("coordinates")]
        public List<List<List<double>>> Coordinates { get; set; }
    }

    public class Point
    {
        [JsonProperty("type")]
        public string Type { get; set; }
        [JsonProperty("coordinates")] 
        public List<double> Coordinates { get; set; }
    }
}